//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShoppyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public decimal ProductPrice { get; set; }
        public string CategoryId { get; set; }
        public Nullable<bool> ExistsInStock { get; set; }
    
        public virtual Catogory Catogory { get; set; }
    }
}
