//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingServiceConsumer.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingItem", Namespace="http://schemas.datacontract.org/2004/07/ShoppingService")]
    [System.SerializableAttribute()]
    public partial class ShoppingItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ItemPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ItemPrice {
            get {
                return this.ItemPriceField;
            }
            set {
                if ((this.ItemPriceField.Equals(value) != true)) {
                    this.ItemPriceField = value;
                    this.RaisePropertyChanged("ItemPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AdditemToCart", ReplyAction="http://tempuri.org/IService1/AdditemToCartResponse")]
        bool AdditemToCart(ShoppingServiceConsumer.ServiceReference1.ShoppingItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AdditemToCart", ReplyAction="http://tempuri.org/IService1/AdditemToCartResponse")]
        System.Threading.Tasks.Task<bool> AdditemToCartAsync(ShoppingServiceConsumer.ServiceReference1.ShoppingItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveItemToCart", ReplyAction="http://tempuri.org/IService1/RemoveItemToCartResponse")]
        bool RemoveItemToCart(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveItemToCart", ReplyAction="http://tempuri.org/IService1/RemoveItemToCartResponse")]
        System.Threading.Tasks.Task<bool> RemoveItemToCartAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowAllItems", ReplyAction="http://tempuri.org/IService1/ShowAllItemsResponse")]
        ShoppingServiceConsumer.ServiceReference1.ShoppingItem[] ShowAllItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowAllItems", ReplyAction="http://tempuri.org/IService1/ShowAllItemsResponse")]
        System.Threading.Tasks.Task<ShoppingServiceConsumer.ServiceReference1.ShoppingItem[]> ShowAllItemsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ShoppingServiceConsumer.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ShoppingServiceConsumer.ServiceReference1.IService1>, ShoppingServiceConsumer.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AdditemToCart(ShoppingServiceConsumer.ServiceReference1.ShoppingItem item) {
            return base.Channel.AdditemToCart(item);
        }
        
        public System.Threading.Tasks.Task<bool> AdditemToCartAsync(ShoppingServiceConsumer.ServiceReference1.ShoppingItem item) {
            return base.Channel.AdditemToCartAsync(item);
        }
        
        public bool RemoveItemToCart(int id) {
            return base.Channel.RemoveItemToCart(id);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveItemToCartAsync(int id) {
            return base.Channel.RemoveItemToCartAsync(id);
        }
        
        public ShoppingServiceConsumer.ServiceReference1.ShoppingItem[] ShowAllItems() {
            return base.Channel.ShowAllItems();
        }
        
        public System.Threading.Tasks.Task<ShoppingServiceConsumer.ServiceReference1.ShoppingItem[]> ShowAllItemsAsync() {
            return base.Channel.ShowAllItemsAsync();
        }
    }
}
